### 필수과제 (다음 주까지 제출)
### 3주차 모두 과제가 다 제출할  수 있음
- sklean에서 제공하는 california housing 데이터 존재 코드 공유 예정
- 집값 다른 여러 피처들이 존재
- 전체 피처를 학습하고 MSE 계산한 것과, 여러분들이 직접 filter 방식으로 상관계수를 통해 피처를 선택해서 학습한 후 mse 비교
- 어떤 피처를 선택했는지, 그리고 추가로 집값에 대한 데이터라 도메인을 좀 더 추가해서 어떤 식으로 선택하면 더 좋을지 추가!

In [54]:
# 필요한 라이브러리 불러오기
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# 캘리포니아 주택 데이터셋 불러오기
california = fetch_california_housing()
X = pd.DataFrame(california.data, columns=california.feature_names)
y = california.target

In [2]:
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [5]:
X.corr()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
MedInc,1.000000,-0.119034,0.326895,-0.062040,0.004834,0.018766,-0.079809,-0.015176
HouseAge,-0.119034,1.000000,-0.153277,-0.077747,-0.296244,0.013191,0.011173,-0.108197
AveRooms,0.326895,-0.153277,1.000000,0.847621,-0.072213,-0.004852,0.106389,-0.027540
AveBedrms,-0.062040,-0.077747,0.847621,1.000000,-0.066197,-0.006181,0.069721,0.013344
Population,0.004834,-0.296244,-0.072213,-0.066197,1.000000,0.069863,-0.108785,0.099773
AveOccup,0.018766,0.013191,-0.004852,-0.006181,0.069863,1.000000,0.002366,0.002476
Latitude,-0.079809,0.011173,0.106389,0.069721,-0.108785,0.002366,1.000000,-0.924664
Longitude,-0.015176,-0.108197,-0.027540,0.013344,0.099773,0.002476,-0.924664,1.000000

In [7]:
corr_matrix = X.corr()['MedInc'].drop('MedInc')
corr_matrix

HouseAge     -0.119034
AveRooms      0.326895
AveBedrms    -0.062040
Population    0.004834
AveOccup      0.018766
Latitude     -0.079809
Longitude    -0.015176
Name: MedInc, dtype: float64

In [50]:
# 특성을 뽑아보기
threshold = 0.3
selected_features = corr_matrix[abs(corr_matrix)>threshold].index
print(selected_features)

Index(['AveRooms'], dtype='object')

In [51]:
#LinearRegression

#데이터 분할 _선택된 피처로
X_selected = X[selected_features]
X_train, X_test, y_train, y_test = train_test_split(X_selected,X['MedInc'],test_size=0.2,random_state=111)

#모델학습
model = LinearRegression()
model.fit(X_train, y_train)

#예측 MSE
y_pred =model.predict(X_test)
mse_selected =mean_squared_error(y_test, y_pred)
print('mse_selected',mse_selected)

mse_selected 3.1103123898344203

In [52]:
##전체 데이터랑 비교하면 

#LinearRegression

#데이터 분할 _선택된 피처로
X_full = X.drop(columns = ['MedInc'])
X_train_full, X_test_full, y_train_full, y_test_full = train_test_split(X_full,X['MedInc'],test_size=0.2,random_state=111)

#모델학습
model_full = LinearRegression()
model_full.fit(X_train_full, y_train_full)

#예측 MSE
y_pred_full =model_full.predict(X_test_full)
mse_full =mean_squared_error(y_test_full, y_pred_full)
print('mse_full',mse_full)

mse_full 1.431706294370832

In [53]:
# 선택 모델 - 전체모델
3.1103123898344203 - 1.431706294370832

1.6786060954635882

- 선택된 모델이 전체 모델보다 성능이 좋지 않음
- 임계값을 조절해 보았으나 전체 모델 성능보다 낮았음